import { selectedCandidates, selectionOptions } from './selection.mjs';
const html = (value) => String(value).replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));

export function renderReviewPage(snapshot, file, now = new Date()) {
  selectionOptions(['--file', file, '--pick', '1']);
  if (!Array.isArray(snapshot?.candidates) || snapshot.candidates.length > 12) throw new Error('候选文件结构无效');
  const cards = snapshot.candidates.map((_, index) => {
    const [item] = selectedCandidates(snapshot, [index + 1], [], now);
    return `<article><label><input type="checkbox" value="${index + 1}"><span>${html(item.title)}</span></label><p class="source">${html(item.source)} · ${html(item.publishedAt.slice(0,10))}</p><p>${html(item.excerpt)}</p><a href="${html(item.url)}" target="_blank" rel="noopener noreferrer" referrerpolicy="no-referrer">阅读原文 ↗</a></article>`;
  }).join('');
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>本地选稿 · JING AI PLAYGROUND</title><style>
*{box-sizing:border-box}body{margin:0;background:#fffdf7;color:#172538;font:16px/1.85 "Microsoft YaHei",sans-serif}main{max-width:1120px;margin:auto;padding:64px 36px 90px}header{max-width:720px;margin-bottom:48px}.brand{font:12px/1.7 Consolas,monospace;letter-spacing:.08em;color:#2457ff}h1{font-size:clamp(30px,4vw,48px);line-height:1.5;margin:18px 0;font-weight:800}h1 span{display:block}h1 mark{background:#ffde4d;color:inherit;padding:0 8px;border-radius:8px}p{margin:16px 0;color:#536174}.layout{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:36px;align-items:start}.cards{display:grid;gap:24px}article{padding:28px;background:white;border:2px solid #172538;border-radius:22px;box-shadow:4px 5px 0 #dce9ff}article:has(input:checked){box-shadow:4px 5px 0 #b9ecd7;border-color:#2457ff}label{display:flex;gap:14px;align-items:baseline;cursor:pointer;font-size:20px;font-weight:700;line-height:1.7}label span{overflow-wrap:anywhere;text-wrap:pretty}input{width:20px;height:20px;flex-shrink:0;accent-color:#2457ff}.source{font-size:12px}a{color:#2457ff;text-underline-offset:4px}aside{position:sticky;top:24px;background:#dce9ff;border:2px solid #172538;border-radius:22px;padding:26px}h2{font-size:22px;margin:0 0 16px}button{font:inherit;border:2px solid #172538;border-radius:12px;background:#ffde4d;padding:10px 16px;cursor:pointer;min-height:44px}button:disabled{opacity:.5;cursor:not-allowed}textarea{width:100%;height:150px;resize:vertical;font:13px/1.7 Consolas,monospace;padding:12px;border:1px solid #172538;border-radius:10px;background:#fff;overflow-wrap:anywhere;margin:16px 0}textarea:focus-visible,a:focus-visible,input:focus-visible,button:focus-visible{outline:3px solid #2457ff;outline-offset:4px}.hint{font-size:13px}#status{min-height:48px}footer{margin-top:36px;font-size:13px;color:#536174}@media(max-width:740px){main{padding:32px 22px 60px}.layout{grid-template-columns:1fr;gap:28px}header{margin-bottom:32px}aside{position:static}article{padding:22px}label{font-size:18px}h1{font-size:30px}}
</style></head><body><main><header><div class="brand">JING AI PLAYGROUND / LOCAL READING DESK</div><h1><span>先读一眼，</span><span>再把<mark>值得写的</mark>留下。</span></h1><p>本地选稿 · 未审核 · 未发布。这里是来源提供的 RSS 摘要，不是全文拆解，也不是荆的观点。</p></header><div class="layout"><section class="cards" aria-label="候选文章">${cards || '<p>没有新的候选，请先运行采集。</p>'}</section><aside><h2>本轮想留下哪些？</h2><p id="count" aria-live="polite">已选 0 / 5 篇</p><p class="hint">勾选后复制免费预检命令，在项目终端运行。网页不会执行命令、调用模型或发布。</p><textarea id="command" aria-label="免费预检命令" readonly placeholder="先勾选一至五篇文章"></textarea><button id="copy" disabled>复制预检命令</button><p id="status" class="hint" role="status"></p><button id="clear" type="button">清空选择</button><p class="hint">此处选择不保存，刷新会清空。预检仍会检查过期和已处理条目；选中不代表已批准发布。</p></aside></div><footer>采集时间：${html(snapshot.fetchedAt)}<br>无配图 · 无付费请求 · 仅本机预览</footer></main><script>
const boxes=[...document.querySelectorAll('input[type=checkbox]')],command=document.getElementById('command'),copy=document.getElementById('copy'),status=document.getElementById('status');
function update(){const chosen=boxes.filter(b=>b.checked).map(b=>b.value);boxes.forEach(b=>b.disabled=chosen.length>=5&&!b.checked);document.getElementById('count').textContent='已选 '+chosen.length+' / 5 篇';command.value=chosen.length?'npm run briefing:draft -- --file ${file} --pick '+chosen.join(',')+' --check':'';copy.disabled=!chosen.length;status.textContent='';}
boxes.forEach(b=>b.addEventListener('change',update));document.getElementById('clear').addEventListener('click',()=>{boxes.forEach(b=>b.checked=false);update()});copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(command.value);status.textContent='已复制免费预检命令；尚未执行。'}catch{command.focus();command.select();status.textContent='无法自动复制，命令已选中，请手动复制。'}});
</script></body></html>`;
}
